// scripts/question-schema.ts
// Auto-generated from Schizodio real collection data (999 NFTs).
// GENERATED: 2026-03-04
//
// CRITICAL: Never change the order of entries -- question_id maps directly
// to a bit position in trait_bitmap. Any reordering breaks the circuit
// and invalidates all stored proofs.
//
// Bitmap layout: [u128; 4] -- 512 bits total, 418 used.
// "No X" values excluded -- bit absent means character lacks that trait.
//
// Bit ranges by trait:
//   Accessories  bits   0-  6 (7 values)
//   Background   bits   7- 95 (89 values)
//   Body         bits  96-105 (10 values)
//   Clothing     bits 106-179 (74 values)
//   Eyebrows     bits 180-192 (13 values)
//   Eyes         bits 193-218 (26 values)
//   Eyewear      bits 219-224 (6 values)
//   Hair         bits 225-256 (32 values)
//   Headwear     bits 257-300 (44 values)
//   Mask         bits 301-302 (2 values)
//   Mouth        bits 303-317 (15 values)
//   Overlays     bits 318-350 (33 values)
//   Sidekick     bits 351-395 (45 values)
//   Weapons      bits 396-417 (22 values)

export type QuestionPredicate = (attrs: Record<string, string>) => boolean;

export const QUESTION_SCHEMA: Record<number, {
  label: string;
  predicate: QuestionPredicate;
}> = {
  // === Accessories ===
    0: { label: 'accessories_backwoods_blunt', predicate: (a) => a['Accessories'] === 'Backwoods Blunt' },
    1: { label: 'accessories_god_candle', predicate: (a) => a['Accessories'] === 'God Candle' },
    2: { label: 'accessories_grime_reaper_candle', predicate: (a) => a['Accessories'] === 'Grime Reaper Candle' },
    3: { label: 'accessories_honey_comb_blunt', predicate: (a) => a['Accessories'] === 'Honey Comb Blunt' },
    4: { label: 'accessories_memory_card_chain', predicate: (a) => a['Accessories'] === 'Memory Card Chain' },
    5: { label: 'accessories_pixelated_ciggy', predicate: (a) => a['Accessories'] === 'Pixelated Ciggy' },
    6: { label: 'accessories_shotgun_shell_chain', predicate: (a) => a['Accessories'] === 'Shotgun Shell Chain' },

  // === Background ===
    7: { label: 'background_a_roads', predicate: (a) => a['Background'] === 'A Roads' },
    8: { label: 'background_akademia_italia', predicate: (a) => a['Background'] === 'Akademia Italia' },
    9: { label: 'background_alotments', predicate: (a) => a['Background'] === 'Alotments' },
   10: { label: 'background_atms_ktms', predicate: (a) => a['Background'] === 'Atms & Ktms' },
   11: { label: 'background_bajan_bando', predicate: (a) => a['Background'] === 'Bajan Bando' },
   12: { label: 'background_bajan_cliff_view', predicate: (a) => a['Background'] === 'Bajan Cliff View' },
   13: { label: 'background_bajan_safehouse', predicate: (a) => a['Background'] === 'Bajan Safehouse' },
   14: { label: 'background_bajan_villa', predicate: (a) => a['Background'] === 'Bajan VIlla' },
   15: { label: 'background_big_pharma', predicate: (a) => a['Background'] === 'Big pharma' },
   16: { label: 'background_bitcoin_broly', predicate: (a) => a['Background'] === 'Bitcoin Broly' },
   17: { label: 'background_black_pool', predicate: (a) => a['Background'] === 'Black Pool' },
   18: { label: 'background_blue_cryptonite', predicate: (a) => a['Background'] === 'Blue Cryptonite' },
   19: { label: 'background_blue_eyes_thunder_dragon', predicate: (a) => a['Background'] === 'Blue Eyes Thunder Dragon ' },
   20: { label: 'background_bonus_stage', predicate: (a) => a['Background'] === 'Bonus stage' },
   21: { label: 'background_cell_games', predicate: (a) => a['Background'] === 'Cell Games' },
   22: { label: 'background_china', predicate: (a) => a['Background'] === 'China ' },
   23: { label: 'background_china_courtyard', predicate: (a) => a['Background'] === 'China Courtyard' },
   24: { label: 'background_chongqing', predicate: (a) => a['Background'] === 'Chongqing' },
   25: { label: 'background_chongqing', predicate: (a) => a['Background'] === 'Chongqing 磁器口古镇 ' },
   26: { label: 'background_chuppa_pillz', predicate: (a) => a['Background'] === 'Chuppa pillz' },
   27: { label: 'background_cloud_nine', predicate: (a) => a['Background'] === 'Cloud Nine' },
   28: { label: 'background_countryside_1', predicate: (a) => a['Background'] === 'CountrySide 1' },
   29: { label: 'background_countryside_2', predicate: (a) => a['Background'] === 'CountrySide 2' },
   30: { label: 'background_county_line', predicate: (a) => a['Background'] === 'County Line' },
   31: { label: 'background_cour_d_honneur', predicate: (a) => a['Background'] === 'Cour d\'honneur' },
   32: { label: 'background_dmt', predicate: (a) => a['Background'] === 'DMT' },
   33: { label: 'background_danube_river', predicate: (a) => a['Background'] === 'Danube River' },
   34: { label: 'background_dubai_desert', predicate: (a) => a['Background'] === 'Dubai Desert' },
   35: { label: 'background_dubai_desert_2', predicate: (a) => a['Background'] === 'Dubai Desert 2' },
   36: { label: 'background_duck_hunt', predicate: (a) => a['Background'] === 'Duck hunt' },
   37: { label: 'background_fenty_bando', predicate: (a) => a['Background'] === 'Fenty Bando' },
   38: { label: 'background_fisherman_s_bastion', predicate: (a) => a['Background'] === 'Fisherman\'s Bastion' },
   39: { label: 'background_five_joints', predicate: (a) => a['Background'] === 'Five joints' },
   40: { label: 'background_fur_za_no_uch_sen', predicate: (a) => a['Background'] === 'Furīza no Uchūsen' },
   41: { label: 'background_hadoken', predicate: (a) => a['Background'] === 'Hadoken 波動拳' },
   42: { label: 'background_honest_werk', predicate: (a) => a['Background'] === 'Honest werk' },
   43: { label: 'background_hong_kong', predicate: (a) => a['Background'] === 'Hong Kong' },
   44: { label: 'background_hongya_cave', predicate: (a) => a['Background'] === 'Hongya Cave 洪崖洞' },
   45: { label: 'background_hyperbolic_timechamber', predicate: (a) => a['Background'] === 'Hyperbolic Timechamber' },
   46: { label: 'background_jiggas_in_paris', predicate: (a) => a['Background'] === 'Jiggas in paris' },
   47: { label: 'background_jumeirah_beach_residence', predicate: (a) => a['Background'] === 'Jumeirah Beach Residence' },
   48: { label: 'background_kong_island', predicate: (a) => a['Background'] === 'Kong Island' },
   49: { label: 'background_light_mist', predicate: (a) => a['Background'] === 'Light & Mist' },
   50: { label: 'background_magyar_llami_operah_z', predicate: (a) => a['Background'] === 'Magyar Állami Operaház' },
   51: { label: 'background_marina_skyline', predicate: (a) => a['Background'] === 'Marina Skyline' },
   52: { label: 'background_marky_b', predicate: (a) => a['Background'] === 'Marky b' },
   53: { label: 'background_mega_drive', predicate: (a) => a['Background'] === 'Mega Drive' },
   54: { label: 'background_money_shot', predicate: (a) => a['Background'] === 'Money Shot' },
   55: { label: 'background_museum_of_the_future', predicate: (a) => a['Background'] === 'Museum of the Future' },
   56: { label: 'background_nycaf', predicate: (a) => a['Background'] === 'NYCafé' },
   57: { label: 'background_nacht_der_untoten', predicate: (a) => a['Background'] === 'Nacht der Untoten' },
   58: { label: 'background_nacht_der_untoten_2', predicate: (a) => a['Background'] === 'Nacht der Untoten 2' },
   59: { label: 'background_nity_ave', predicate: (a) => a['Background'] === 'Nity Ave' },
   60: { label: 'background_open_sea', predicate: (a) => a['Background'] === 'Open Sea' },
   61: { label: 'background_open_sea_2', predicate: (a) => a['Background'] === 'Open Sea 2' },
   62: { label: 'background_palm_jumeirah', predicate: (a) => a['Background'] === 'Palm Jumeirah' },
   63: { label: 'background_paradise_1', predicate: (a) => a['Background'] === 'Paradise 1' },
   64: { label: 'background_paradise_2', predicate: (a) => a['Background'] === 'Paradise 2' },
   65: { label: 'background_paradise_3', predicate: (a) => a['Background'] === 'Paradise 3' },
   66: { label: 'background_paradise_4', predicate: (a) => a['Background'] === 'Paradise 4' },
   67: { label: 'background_paradise_5', predicate: (a) => a['Background'] === 'Paradise 5' },
   68: { label: 'background_paradise_6', predicate: (a) => a['Background'] === 'Paradise 6' },
   69: { label: 'background_pepe_pillz', predicate: (a) => a['Background'] === 'Pepe Pillz' },
   70: { label: 'background_phantom', predicate: (a) => a['Background'] === 'Phantom' },
   71: { label: 'background_pick_n_mix', predicate: (a) => a['Background'] === 'Pick\'n Mix' },
   72: { label: 'background_pink_champagne', predicate: (a) => a['Background'] === 'Pink Champagne' },
   73: { label: 'background_planet_kai', predicate: (a) => a['Background'] === 'Planet Kai' },
   74: { label: 'background_raffles_city', predicate: (a) => a['Background'] === 'Raffles City' },
   75: { label: 'background_rekt_bardock', predicate: (a) => a['Background'] === 'Rekt Bardock' },
   76: { label: 'background_richard_haynes_boardwalk', predicate: (a) => a['Background'] === 'Richard Haynes Boardwalk' },
   77: { label: 'background_snes_cartridge', predicate: (a) => a['Background'] === 'SNES Cartridge' },
   78: { label: 'background_schizo_yoshi_kart', predicate: (a) => a['Background'] === 'Schizo Yoshi Kart' },
   79: { label: 'background_shang_tsung_s_palace', predicate: (a) => a['Background'] === 'Shang Tsung’s Palace' },
   80: { label: 'background_sleepy_hollow', predicate: (a) => a['Background'] === 'Sleepy Hollow' },
   81: { label: 'background_star_dawg', predicate: (a) => a['Background'] === 'Star Dawg' },
   82: { label: 'background_sz_chenyi_l_nch_d', predicate: (a) => a['Background'] === 'Széchenyi Lánchíd' },
   83: { label: 'background_tesla_pillz', predicate: (a) => a['Background'] === 'Tesla Pillz' },
   84: { label: 'background_the_canal', predicate: (a) => a['Background'] === 'The Canal' },
   85: { label: 'background_the_endz_2', predicate: (a) => a['Background'] === 'The Endz 2' },
   86: { label: 'background_the_marina', predicate: (a) => a['Background'] === 'The Marina' },
   87: { label: 'background_the_office_szn1', predicate: (a) => a['Background'] === 'The Office SZN1' },
   88: { label: 'background_the_office_szn2', predicate: (a) => a['Background'] === 'The Office SZN2' },
   89: { label: 'background_the_peak', predicate: (a) => a['Background'] === 'The Peak' },
   90: { label: 'background_the_pit', predicate: (a) => a['Background'] === 'The Pit' },
   91: { label: 'background_the_endz', predicate: (a) => a['Background'] === 'The endz' },
   92: { label: 'background_touch_grass', predicate: (a) => a['Background'] === 'Touch grass' },
   93: { label: 'background_ups_pillz', predicate: (a) => a['Background'] === 'UPS pillz' },
   94: { label: 'background_white_widow', predicate: (a) => a['Background'] === 'White Widow' },
   95: { label: 'background_yangtze_river', predicate: (a) => a['Background'] === 'Yangtze River' },

  // === Body ===
   96: { label: 'body_boy_who_cried_wolf', predicate: (a) => a['Body'] === 'Boy Who Cried Wolf' },
   97: { label: 'body_brother', predicate: (a) => a['Body'] === 'Brother' },
   98: { label: 'body_gora', predicate: (a) => a['Body'] === 'Gora' },
   99: { label: 'body_greeny', predicate: (a) => a['Body'] === 'Greeny' },
  100: { label: 'body_lobster_pink', predicate: (a) => a['Body'] === 'Lobster Pink' },
  101: { label: 'body_purple_urkle', predicate: (a) => a['Body'] === 'Purple Urkle' },
  102: { label: 'body_schizo_blue', predicate: (a) => a['Body'] === 'Schizo Blue' },
  103: { label: 'body_schizo_panda', predicate: (a) => a['Body'] === 'Schizo Panda' },
  104: { label: 'body_snowflake', predicate: (a) => a['Body'] === 'Snowflake' },
  105: { label: 'body_stone_cyborg', predicate: (a) => a['Body'] === 'Stone Cyborg' },

  // === Clothing ===
  106: { label: 'clothing_adhd_tshirt', predicate: (a) => a['Clothing'] === 'ADHD Tshirt' },
  107: { label: 'clothing_agbada_tshirt', predicate: (a) => a['Clothing'] === 'Agbada Tshirt' },
  108: { label: 'clothing_apestar_jacket', predicate: (a) => a['Clothing'] === 'Apestar Jacket' },
  109: { label: 'clothing_argent_tshirt', predicate: (a) => a['Clothing'] === 'Argent Tshirt' },
  110: { label: 'clothing_autism_jumper', predicate: (a) => a['Clothing'] === 'Autism Jumper' },
  111: { label: 'clothing_baby_schizo_pink_tshirt', predicate: (a) => a['Clothing'] === 'Baby Schizo Pink Tshirt' },
  112: { label: 'clothing_baby_schizo_white_tshirt', predicate: (a) => a['Clothing'] === 'Baby Schizo White Tshirt' },
  113: { label: 'clothing_backwoods_hoodie', predicate: (a) => a['Clothing'] === 'Backwoods Hoodie' },
  114: { label: 'clothing_bitchari_t_shirt', predicate: (a) => a['Clothing'] === 'Bitchari T shirt' },
  115: { label: 'clothing_black_jacket', predicate: (a) => a['Clothing'] === 'Black Jacket' },
  116: { label: 'clothing_blue_puffer', predicate: (a) => a['Clothing'] === 'Blue Puffer' },
  117: { label: 'clothing_bob_sponge_tshirt', predicate: (a) => a['Clothing'] === 'Bob Sponge Tshirt' },
  118: { label: 'clothing_chaatgpt_tshirt', predicate: (a) => a['Clothing'] === 'Chaatgpt Tshirt' },
  119: { label: 'clothing_ethlend_tshirt', predicate: (a) => a['Clothing'] === 'ETHLend Tshirt' },
  120: { label: 'clothing_ekubo_tshirt', predicate: (a) => a['Clothing'] === 'Ekubo Tshirt' },
  121: { label: 'clothing_faguar_tshirt', predicate: (a) => a['Clothing'] === 'Faguar Tshirt' },
  122: { label: 'clothing_flintstones_tshirt', predicate: (a) => a['Clothing'] === 'Flintstones Tshirt' },
  123: { label: 'clothing_get_money_tshirt', predicate: (a) => a['Clothing'] === 'Get Money Tshirt' },
  124: { label: 'clothing_gods_strongest_schizo', predicate: (a) => a['Clothing'] === 'Gods Strongest Schizo' },
  125: { label: 'clothing_gold_skull_shirt', predicate: (a) => a['Clothing'] === 'Gold Skull Shirt' },
  126: { label: 'clothing_golden_boy_tracksuit', predicate: (a) => a['Clothing'] === 'Golden Boy Tracksuit' },
  127: { label: 'clothing_goochi_track_jacket', predicate: (a) => a['Clothing'] === 'Goochi Track Jacket' },
  128: { label: 'clothing_guru_suit', predicate: (a) => a['Clothing'] === 'Guru Suit' },
  129: { label: 'clothing_i_am_carrying_tshirt', predicate: (a) => a['Clothing'] === 'I Am Carrying Tshirt' },
  130: { label: 'clothing_i_have_a_weapon', predicate: (a) => a['Clothing'] === 'I Have A Weapon' },
  131: { label: 'clothing_im_with_schizodio_tshirt', predicate: (a) => a['Clothing'] === 'Im with Schizodio Tshirt' },
  132: { label: 'clothing_israeli_coin_tshirt', predicate: (a) => a['Clothing'] === 'Israeli Coin Tshirt' },
  133: { label: 'clothing_krusty_tshirt', predicate: (a) => a['Clothing'] === 'Krusty Tshirt' },
  134: { label: 'clothing_kurta_jeet', predicate: (a) => a['Clothing'] === 'Kurta Jeet' },
  135: { label: 'clothing_life_is_soup_tshirt', predicate: (a) => a['Clothing'] === 'Life is Soup Tshirt' },
  136: { label: 'clothing_love_nigeria_tshirt', predicate: (a) => a['Clothing'] === 'Love Nigeria Tshirt' },
  137: { label: 'clothing_luv_cobie_tshirt', predicate: (a) => a['Clothing'] === 'Luv Cobie Tshirt' },
  138: { label: 'clothing_mushroom_jacket', predicate: (a) => a['Clothing'] === 'Mushroom Jacket' },
  139: { label: 'clothing_mushroomon_jacket', predicate: (a) => a['Clothing'] === 'Mushroomon Jacket' },
  140: { label: 'clothing_okay_now_tshirt', predicate: (a) => a['Clothing'] === 'Okay Now Tshirt' },
  141: { label: 'clothing_paradex_tshirt', predicate: (a) => a['Clothing'] === 'Paradex Tshirt' },
  142: { label: 'clothing_peaky_blind_tshirt', predicate: (a) => a['Clothing'] === 'Peaky Blind Tshirt' },
  143: { label: 'clothing_pink_puffer', predicate: (a) => a['Clothing'] === 'Pink Puffer' },
  144: { label: 'clothing_polymarket_tshirt', predicate: (a) => a['Clothing'] === 'Polymarket Tshirt' },
  145: { label: 'clothing_puff_tshirt', predicate: (a) => a['Clothing'] === 'Puff Tshirt' },
  146: { label: 'clothing_purple_aki_tshirt', predicate: (a) => a['Clothing'] === 'Purple Aki Tshirt ' },
  147: { label: 'clothing_purple_tuxedo', predicate: (a) => a['Clothing'] === 'Purple Tuxedo' },
  148: { label: 'clothing_relax_vest', predicate: (a) => a['Clothing'] === 'Relax Vest' },
  149: { label: 'clothing_remilia_jacket', predicate: (a) => a['Clothing'] === 'Remilia Jacket' },
  150: { label: 'clothing_slm_tshirt', predicate: (a) => a['Clothing'] === 'SLM Tshirt' },
  151: { label: 'clothing_saiyan_suit', predicate: (a) => a['Clothing'] === 'Saiyan Suit' },
  152: { label: 'clothing_scared_of_women', predicate: (a) => a['Clothing'] === 'Scared of Women' },
  153: { label: 'clothing_schizario_tshirt', predicate: (a) => a['Clothing'] === 'Schizario Tshirt' },
  154: { label: 'clothing_schizo_duck_tshirt', predicate: (a) => a['Clothing'] === 'Schizo Duck Tshirt' },
  155: { label: 'clothing_schizo_game_tshirt', predicate: (a) => a['Clothing'] === 'Schizo Game Tshirt' },
  156: { label: 'clothing_schizo_hut_tshirt', predicate: (a) => a['Clothing'] === 'Schizo Hut Tshirt' },
  157: { label: 'clothing_schizo_network_tshirt', predicate: (a) => a['Clothing'] === 'Schizo Network Tshirt' },
  158: { label: 'clothing_schizo_red_tshirt', predicate: (a) => a['Clothing'] === 'Schizo Red Tshirt' },
  159: { label: 'clothing_schizo_tunez_tshirt', predicate: (a) => a['Clothing'] === 'Schizo Tunez Tshirt' },
  160: { label: 'clothing_schizoberry_tshirt', predicate: (a) => a['Clothing'] === 'Schizoberry Tshirt' },
  161: { label: 'clothing_schizodio_company_blue_tshirt', predicate: (a) => a['Clothing'] === 'Schizodio Company Blue Tshirt' },
  162: { label: 'clothing_schizodio_company_brown_tshirt', predicate: (a) => a['Clothing'] === 'Schizodio Company Brown Tshirt' },
  163: { label: 'clothing_school_uniform', predicate: (a) => a['Clothing'] === 'School Uniform' },
  164: { label: 'clothing_spider_tshirt', predicate: (a) => a['Clothing'] === 'Spider Tshirt' },
  165: { label: 'clothing_squid_jacket', predicate: (a) => a['Clothing'] === 'Squid Jacket' },
  166: { label: 'clothing_starkware_alf_tshirt', predicate: (a) => a['Clothing'] === 'StarkWare Alf Tshirt' },
  167: { label: 'clothing_starknet_tshirt', predicate: (a) => a['Clothing'] === 'Starknet Tshirt' },
  168: { label: 'clothing_stoney_puffer', predicate: (a) => a['Clothing'] === 'Stoney Puffer' },
  169: { label: 'clothing_stop_being_poor_vest', predicate: (a) => a['Clothing'] === 'Stop Being Poor Vest' },
  170: { label: 'clothing_strapped_schizo_tshirt', predicate: (a) => a['Clothing'] === 'Strapped Schizo Tshirt' },
  171: { label: 'clothing_tamil_tiger_tshirt', predicate: (a) => a['Clothing'] === 'Tamil Tiger Tshirt' },
  172: { label: 'clothing_they_tshirt', predicate: (a) => a['Clothing'] === 'They Tshirt' },
  173: { label: 'clothing_turkey_camo_tshirt', predicate: (a) => a['Clothing'] === 'Turkey Camo Tshirt' },
  174: { label: 'clothing_turkey_track_jacket', predicate: (a) => a['Clothing'] === 'Turkey Track Jacket' },
  175: { label: 'clothing_turquoise_tuxedo', predicate: (a) => a['Clothing'] === 'Turquoise Tuxedo' },
  176: { label: 'clothing_tuxedo', predicate: (a) => a['Clothing'] === 'Tuxedo' },
  177: { label: 'clothing_venom_suit', predicate: (a) => a['Clothing'] === 'Venom Suit' },
  178: { label: 'clothing_xverse_tshirt', predicate: (a) => a['Clothing'] === 'Xverse Tshirt' },
  179: { label: 'clothing_zero_tshirt', predicate: (a) => a['Clothing'] === 'Zero Tshirt' },

  // === Eyebrows ===
  180: { label: 'eyebrows_black_notched_slits', predicate: (a) => a['Eyebrows'] === 'Black Notched Slits' },
  181: { label: 'eyebrows_black_slits', predicate: (a) => a['Eyebrows'] === 'Black Slits' },
  182: { label: 'eyebrows_blue_notched_slit', predicate: (a) => a['Eyebrows'] === 'Blue Notched Slit' },
  183: { label: 'eyebrows_cyan_camo', predicate: (a) => a['Eyebrows'] === 'Cyan Camo' },
  184: { label: 'eyebrows_funky', predicate: (a) => a['Eyebrows'] === 'Funky' },
  185: { label: 'eyebrows_purple_camo', predicate: (a) => a['Eyebrows'] === 'Purple Camo' },
  186: { label: 'eyebrows_purple_slits', predicate: (a) => a['Eyebrows'] === 'Purple Slits' },
  187: { label: 'eyebrows_red_eyebrows', predicate: (a) => a['Eyebrows'] === 'Red Eyebrows ' },
  188: { label: 'eyebrows_sad', predicate: (a) => a['Eyebrows'] === 'Sad' },
  189: { label: 'eyebrows_schizodio_blue', predicate: (a) => a['Eyebrows'] === 'Schizodio Blue' },
  190: { label: 'eyebrows_standard', predicate: (a) => a['Eyebrows'] === 'Standard' },
  191: { label: 'eyebrows_standard_2', predicate: (a) => a['Eyebrows'] === 'Standard 2' },
  192: { label: 'eyebrows_tinted_green_notched_slit', predicate: (a) => a['Eyebrows'] === 'Tinted Green Notched Slit' },

  // === Eyes ===
  193: { label: 'eyes_blood_shot', predicate: (a) => a['Eyes'] === 'Blood Shot' },
  194: { label: 'eyes_confusion', predicate: (a) => a['Eyes'] === 'Confusion' },
  195: { label: 'eyes_crying', predicate: (a) => a['Eyes'] === 'Crying' },
  196: { label: 'eyes_dead', predicate: (a) => a['Eyes'] === 'Dead' },
  197: { label: 'eyes_dead_splash', predicate: (a) => a['Eyes'] === 'Dead Splash' },
  198: { label: 'eyes_ekubo_bionic_eyes', predicate: (a) => a['Eyes'] === 'Ekubo Bionic Eyes' },
  199: { label: 'eyes_fire_devil', predicate: (a) => a['Eyes'] === 'Fire Devil' },
  200: { label: 'eyes_four_spots', predicate: (a) => a['Eyes'] === 'Four Spots' },
  201: { label: 'eyes_green_pilled', predicate: (a) => a['Eyes'] === 'Green Pilled' },
  202: { label: 'eyes_hazelnut', predicate: (a) => a['Eyes'] === 'Hazelnut' },
  203: { label: 'eyes_kano_s_bionic_eyes', predicate: (a) => a['Eyes'] === 'Kano\'s Bionic Eyes' },
  204: { label: 'eyes_milady_blue', predicate: (a) => a['Eyes'] === 'Milady Blue' },
  205: { label: 'eyes_milady_green', predicate: (a) => a['Eyes'] === 'Milady Green' },
  206: { label: 'eyes_milady_schizo_tattoo', predicate: (a) => a['Eyes'] === 'Milady Schizo Tattoo' },
  207: { label: 'eyes_purple_urkle', predicate: (a) => a['Eyes'] === 'Purple Urkle' },
  208: { label: 'eyes_remilio_light_green', predicate: (a) => a['Eyes'] === 'Remilio Light Green' },
  209: { label: 'eyes_reptilian_red', predicate: (a) => a['Eyes'] === 'Reptilian Red' },
  210: { label: 'eyes_schizo_green', predicate: (a) => a['Eyes'] === 'Schizo Green' },
  211: { label: 'eyes_schizo_light_blue', predicate: (a) => a['Eyes'] === 'Schizo Light Blue' },
  212: { label: 'eyes_schizo_og_white', predicate: (a) => a['Eyes'] === 'Schizo OG White' },
  213: { label: 'eyes_schizo_purple', predicate: (a) => a['Eyes'] === 'Schizo Purple' },
  214: { label: 'eyes_schizo_red', predicate: (a) => a['Eyes'] === 'Schizo Red' },
  215: { label: 'eyes_schizo_tattoo_eyes', predicate: (a) => a['Eyes'] === 'Schizo Tattoo Eyes' },
  216: { label: 'eyes_schizo_yellow', predicate: (a) => a['Eyes'] === 'Schizo Yellow' },
  217: { label: 'eyes_stoned_red', predicate: (a) => a['Eyes'] === 'Stoned Red' },
  218: { label: 'eyes_whirlpool', predicate: (a) => a['Eyes'] === 'Whirlpool' },

  // === Eyewear ===
  219: { label: 'eyewear_safety_glasses_blue', predicate: (a) => a['Eyewear'] === 'Safety Glasses Blue' },
  220: { label: 'eyewear_safety_glasses_green', predicate: (a) => a['Eyewear'] === 'Safety Glasses Green' },
  221: { label: 'eyewear_safety_glasses_orange', predicate: (a) => a['Eyewear'] === 'Safety Glasses Orange' },
  222: { label: 'eyewear_safety_glasses_pink', predicate: (a) => a['Eyewear'] === 'Safety Glasses Pink' },
  223: { label: 'eyewear_safety_glasses_purple', predicate: (a) => a['Eyewear'] === 'Safety Glasses Purple' },
  224: { label: 'eyewear_schizo_scouter', predicate: (a) => a['Eyewear'] === 'Schizo Scouter' },

  // === Hair ===
  225: { label: 'hair_black_jellycut', predicate: (a) => a['Hair'] === 'Black Jellycut' },
  226: { label: 'hair_black_pompadour', predicate: (a) => a['Hair'] === 'Black Pompadour' },
  227: { label: 'hair_blondie_brown_pompadour', predicate: (a) => a['Hair'] === 'Blondie Brown Pompadour' },
  228: { label: 'hair_blue_sherbert_fringe_flow', predicate: (a) => a['Hair'] === 'Blue Sherbert Fringe Flow' },
  229: { label: 'hair_brown_curtain_bob', predicate: (a) => a['Hair'] === 'Brown Curtain Bob' },
  230: { label: 'hair_brown_fringe_flow', predicate: (a) => a['Hair'] === 'Brown Fringe Flow' },
  231: { label: 'hair_cyan_blue_pompadour', predicate: (a) => a['Hair'] === 'Cyan Blue Pompadour' },
  232: { label: 'hair_dark_green_jelly_cut', predicate: (a) => a['Hair'] === 'Dark Green Jelly Cut' },
  233: { label: 'hair_dark_red_fringe_flow', predicate: (a) => a['Hair'] === 'Dark Red Fringe Flow' },
  234: { label: 'hair_fringe_cyan', predicate: (a) => a['Hair'] === 'Fringe Cyan' },
  235: { label: 'hair_fringe_pink', predicate: (a) => a['Hair'] === 'Fringe Pink' },
  236: { label: 'hair_fringe_white', predicate: (a) => a['Hair'] === 'Fringe White' },
  237: { label: 'hair_ginger_curtain_bob', predicate: (a) => a['Hair'] === 'Ginger Curtain Bob' },
  238: { label: 'hair_green_fringe_flow', predicate: (a) => a['Hair'] === 'Green Fringe Flow' },
  239: { label: 'hair_green_jellycut', predicate: (a) => a['Hair'] === 'Green Jellycut' },
  240: { label: 'hair_light_blonde_pompadour', predicate: (a) => a['Hair'] === 'Light Blonde Pompadour' },
  241: { label: 'hair_milady_black', predicate: (a) => a['Hair'] === 'Milady Black' },
  242: { label: 'hair_milady_dark_blue', predicate: (a) => a['Hair'] === 'Milady Dark Blue' },
  243: { label: 'hair_milady_green', predicate: (a) => a['Hair'] === 'Milady Green' },
  244: { label: 'hair_milady_red', predicate: (a) => a['Hair'] === 'Milady Red' },
  245: { label: 'hair_purple_curtain_bob', predicate: (a) => a['Hair'] === 'Purple Curtain Bob' },
  246: { label: 'hair_purple_pompadour', predicate: (a) => a['Hair'] === 'Purple Pompadour' },
  247: { label: 'hair_quan_orange', predicate: (a) => a['Hair'] === 'Quan Orange' },
  248: { label: 'hair_quan_pink', predicate: (a) => a['Hair'] === 'Quan Pink' },
  249: { label: 'hair_quan_red_black', predicate: (a) => a['Hair'] === 'Quan Red Black' },
  250: { label: 'hair_rainbow_curtain_bob', predicate: (a) => a['Hair'] === 'Rainbow Curtain Bob' },
  251: { label: 'hair_rainbow_sherbet_fringe_flow', predicate: (a) => a['Hair'] === 'Rainbow Sherbet Fringe Flow' },
  252: { label: 'hair_red_jellycut', predicate: (a) => a['Hair'] === 'Red Jellycut' },
  253: { label: 'hair_remilio_madoka', predicate: (a) => a['Hair'] === 'Remilio Madoka' },
  254: { label: 'hair_remilio_madoka_red', predicate: (a) => a['Hair'] === 'Remilio Madoka Red' },
  255: { label: 'hair_white_jellycut', predicate: (a) => a['Hair'] === 'White Jellycut' },
  256: { label: 'hair_yellowy_orange_curtain_bob', predicate: (a) => a['Hair'] === 'Yellowy Orange Curtain Bob' },

  // === Headwear ===
  257: { label: 'headwear_90s_trapstar', predicate: (a) => a['Headwear'] === '90s Trapstar' },
  258: { label: 'headwear_birka_red', predicate: (a) => a['Headwear'] === 'Birka Red' },
  259: { label: 'headwear_clown_headwarmer', predicate: (a) => a['Headwear'] === 'Clown Headwarmer' },
  260: { label: 'headwear_eth_hodl_cap', predicate: (a) => a['Headwear'] === 'ETH HODL Cap' },
  261: { label: 'headwear_ekubo_cap', predicate: (a) => a['Headwear'] === 'Ekubo Cap' },
  262: { label: 'headwear_espeon_beaniee', predicate: (a) => a['Headwear'] === 'Espeon Beaniee' },
  263: { label: 'headwear_fedora_hat', predicate: (a) => a['Headwear'] === 'Fedora Hat' },
  264: { label: 'headwear_frieza_helmet', predicate: (a) => a['Headwear'] === 'Frieza Helmet' },
  265: { label: 'headwear_frog_hat', predicate: (a) => a['Headwear'] === 'Frog Hat' },
  266: { label: 'headwear_frogsplash_winterhat', predicate: (a) => a['Headwear'] === 'Frogsplash Winterhat' },
  267: { label: 'headwear_fwog_hybrid_hat', predicate: (a) => a['Headwear'] === 'Fwog Hybrid Hat' },
  268: { label: 'headwear_gengar_winterhat', predicate: (a) => a['Headwear'] === 'Gengar Winterhat' },
  269: { label: 'headwear_hex_cap', predicate: (a) => a['Headwear'] === 'HEX Cap' },
  270: { label: 'headwear_hodl_btc_cap', predicate: (a) => a['Headwear'] === 'HODL Btc Cap' },
  271: { label: 'headwear_halo', predicate: (a) => a['Headwear'] === 'Halo' },
  272: { label: 'headwear_ikea_bucket_hat', predicate: (a) => a['Headwear'] === 'IKEA Bucket Hat' },
  273: { label: 'headwear_jamaican_clown_headwarmer', predicate: (a) => a['Headwear'] === 'Jamaican Clown Headwarmer' },
  274: { label: 'headwear_jesus_cross_cap', predicate: (a) => a['Headwear'] === 'Jesus Cross Cap' },
  275: { label: 'headwear_msga_cap', predicate: (a) => a['Headwear'] === 'MSGA Cap' },
  276: { label: 'headwear_monster_ink_bucket_hat', predicate: (a) => a['Headwear'] === 'Monster Ink Bucket Hat' },
  277: { label: 'headwear_nigerian_clown_headwarmer', predicate: (a) => a['Headwear'] === 'Nigerian Clown Headwarmer' },
  278: { label: 'headwear_oasis_cap', predicate: (a) => a['Headwear'] === 'Oasis Cap' },
  279: { label: 'headwear_pepe_indian_russian_hat', predicate: (a) => a['Headwear'] === 'Pepe Indian Russian Hat' },
  280: { label: 'headwear_pika_hat', predicate: (a) => a['Headwear'] === 'Pika Hat' },
  281: { label: 'headwear_polymarket_cap', predicate: (a) => a['Headwear'] === 'Polymarket Cap' },
  282: { label: 'headwear_rainbow_squid_hat', predicate: (a) => a['Headwear'] === 'Rainbow Squid Hat' },
  283: { label: 'headwear_remilia_black_cap', predicate: (a) => a['Headwear'] === 'Remilia Black Cap' },
  284: { label: 'headwear_remilia_cap', predicate: (a) => a['Headwear'] === 'Remilia Cap' },
  285: { label: 'headwear_remilia_greeny_gold_cap', predicate: (a) => a['Headwear'] === 'Remilia Greeny Gold Cap' },
  286: { label: 'headwear_ronnie_beanie', predicate: (a) => a['Headwear'] === 'Ronnie Beanie' },
  287: { label: 'headwear_schizodio_bucket_hat', predicate: (a) => a['Headwear'] === 'Schizodio Bucket Hat' },
  288: { label: 'headwear_schizodio_headband', predicate: (a) => a['Headwear'] === 'Schizodio Headband ' },
  289: { label: 'headwear_slink_cap', predicate: (a) => a['Headwear'] === 'Slink Cap' },
  290: { label: 'headwear_sonic_beanie', predicate: (a) => a['Headwear'] === 'Sonic Beanie' },
  291: { label: 'headwear_starknet_pirate_hat', predicate: (a) => a['Headwear'] === 'Starknet Pirate Hat' },
  292: { label: 'headwear_strawberry_winterhat', predicate: (a) => a['Headwear'] === 'Strawberry Winterhat' },
  293: { label: 'headwear_stwo_cap', predicate: (a) => a['Headwear'] === 'Stwo Cap' },
  294: { label: 'headwear_tinchu_hat', predicate: (a) => a['Headwear'] === 'Tinchu Hat' },
  295: { label: 'headwear_toy_alien_cap', predicate: (a) => a['Headwear'] === 'Toy Alien Cap' },
  296: { label: 'headwear_turban', predicate: (a) => a['Headwear'] === 'Turban' },
  297: { label: 'headwear_uganda_schizo_cap', predicate: (a) => a['Headwear'] === 'Uganda Schizo Cap' },
  298: { label: 'headwear_umbreon_beanie', predicate: (a) => a['Headwear'] === 'Umbreon Beanie ' },
  299: { label: 'headwear_wif_beanie', predicate: (a) => a['Headwear'] === 'Wif Beanie' },
  300: { label: 'headwear_xverse_cap', predicate: (a) => a['Headwear'] === 'Xverse Cap' },

  // === Mask ===
  301: { label: 'mask_cyborg_hypio', predicate: (a) => a['Mask'] === 'Cyborg Hypio' },
  302: { label: 'mask_schizodio_og_mask', predicate: (a) => a['Mask'] === 'Schizodio OG Mask' },

  // === Mouth ===
  303: { label: 'mouth_happy', predicate: (a) => a['Mouth'] === 'Happy' },
  304: { label: 'mouth_neutral', predicate: (a) => a['Mouth'] === 'Neutral' },
  305: { label: 'mouth_open', predicate: (a) => a['Mouth'] === 'Open' },
  306: { label: 'mouth_rectangle', predicate: (a) => a['Mouth'] === 'Rectangle' },
  307: { label: 'mouth_smiley', predicate: (a) => a['Mouth'] === 'Smiley' },
  308: { label: 'mouth_squiggle', predicate: (a) => a['Mouth'] === 'Squiggle' },
  309: { label: 'mouth_squiggly', predicate: (a) => a['Mouth'] === 'Squiggly' },
  310: { label: 'mouth_squiggly_blue', predicate: (a) => a['Mouth'] === 'Squiggly Blue' },
  311: { label: 'mouth_symbiote', predicate: (a) => a['Mouth'] === 'Symbiote' },
  312: { label: 'mouth_u', predicate: (a) => a['Mouth'] === 'U' },
  313: { label: 'mouth_u_blue', predicate: (a) => a['Mouth'] === 'U Blue' },
  314: { label: 'mouth_v', predicate: (a) => a['Mouth'] === 'V' },
  315: { label: 'mouth_v_blue', predicate: (a) => a['Mouth'] === 'V Blue' },
  316: { label: 'mouth_w', predicate: (a) => a['Mouth'] === 'W' },
  317: { label: 'mouth_w_red', predicate: (a) => a['Mouth'] === 'W Red' },

  // === Overlays ===
  318: { label: 'overlays_abdel_called_me', predicate: (a) => a['Overlays'] === 'Abdel Called Me' },
  319: { label: 'overlays_alexa_hears', predicate: (a) => a['Overlays'] === 'Alexa Hears' },
  320: { label: 'overlays_bastard_guy', predicate: (a) => a['Overlays'] === 'Bastard Guy' },
  321: { label: 'overlays_black_panther_tamil_tiger', predicate: (a) => a['Overlays'] === 'Black Panther Tamil Tiger' },
  322: { label: 'overlays_downstairs_upstairs', predicate: (a) => a['Overlays'] === 'Downstairs Upstairs' },
  323: { label: 'overlays_duck_hunt_cartridge', predicate: (a) => a['Overlays'] === 'Duck Hunt Cartridge' },
  324: { label: 'overlays_eating_the_pets', predicate: (a) => a['Overlays'] === 'Eating The Pets' },
  325: { label: 'overlays_hai_hai', predicate: (a) => a['Overlays'] === 'Hai Hai' },
  326: { label: 'overlays_happy_schizo_pack', predicate: (a) => a['Overlays'] === 'Happy Schizo Pack' },
  327: { label: 'overlays_i_believed_in_something', predicate: (a) => a['Overlays'] === 'I Believed in Something' },
  328: { label: 'overlays_i_just_got_skemmed', predicate: (a) => a['Overlays'] === 'I Just Got Skemmed' },
  329: { label: 'overlays_i_never_rugged', predicate: (a) => a['Overlays'] === 'I Never Rugged' },
  330: { label: 'overlays_i_is_carrying', predicate: (a) => a['Overlays'] === 'I is Carrying' },
  331: { label: 'overlays_is_my_bitch', predicate: (a) => a['Overlays'] === 'Is My Bitch' },
  332: { label: 'overlays_it_s_not_illegal', predicate: (a) => a['Overlays'] === 'It\'s Not Illegal' },
  333: { label: 'overlays_milady_munchies', predicate: (a) => a['Overlays'] === 'Milady Munchies' },
  334: { label: 'overlays_nigerian_gun_fingers', predicate: (a) => a['Overlays'] === 'Nigerian Gun Fingers' },
  335: { label: 'overlays_punk_ass_schizo', predicate: (a) => a['Overlays'] === 'Punk Ass Schizo' },
  336: { label: 'overlays_schizo_cali_pack', predicate: (a) => a['Overlays'] === 'Schizo Cali Pack' },
  337: { label: 'overlays_schizo_headshot', predicate: (a) => a['Overlays'] === 'Schizo Headshot' },
  338: { label: 'overlays_schizo_mylar_pack', predicate: (a) => a['Overlays'] === 'Schizo Mylar Pack' },
  339: { label: 'overlays_sherbinski', predicate: (a) => a['Overlays'] === 'Sherbinski' },
  340: { label: 'overlays_there_is_a_meme', predicate: (a) => a['Overlays'] === 'There is a Meme' },
  341: { label: 'overlays_this_my_jigga', predicate: (a) => a['Overlays'] === 'This My Jigga' },
  342: { label: 'overlays_turkey_twizzlers', predicate: (a) => a['Overlays'] === 'Turkey Twizzlers' },
  343: { label: 'overlays_turkish_barber', predicate: (a) => a['Overlays'] === 'Turkish Barber' },
  344: { label: 'overlays_wmt', predicate: (a) => a['Overlays'] === 'WMT' },
  345: { label: 'overlays_why_so_serious', predicate: (a) => a['Overlays'] === 'Why So Serious' },
  346: { label: 'overlays_winmeth', predicate: (a) => a['Overlays'] === 'Winmeth' },
  347: { label: 'overlays_you_will_never_find_me', predicate: (a) => a['Overlays'] === 'You Will Never Find Me' },
  348: { label: 'overlays_your_soul_is_mine', predicate: (a) => a['Overlays'] === 'Your Soul is Mine' },
  349: { label: 'overlays_zabubu_pack', predicate: (a) => a['Overlays'] === 'Zabubu Pack' },
  350: { label: 'overlays_isupport', predicate: (a) => a['Overlays'] === 'iSupport' },

  // === Sidekick ===
  351: { label: 'sidekick_alf', predicate: (a) => a['Sidekick'] === 'Alf' },
  352: { label: 'sidekick_arnesh', predicate: (a) => a['Sidekick'] === 'Arnesh' },
  353: { label: 'sidekick_baboon', predicate: (a) => a['Sidekick'] === 'Baboon' },
  354: { label: 'sidekick_bernard', predicate: (a) => a['Sidekick'] === 'Bernard' },
  355: { label: 'sidekick_billy_no_mates', predicate: (a) => a['Sidekick'] === 'Billy no Mates' },
  356: { label: 'sidekick_black_kangal', predicate: (a) => a['Sidekick'] === 'Black Kangal' },
  357: { label: 'sidekick_blanka', predicate: (a) => a['Sidekick'] === 'Blanka' },
  358: { label: 'sidekick_blobby', predicate: (a) => a['Sidekick'] === 'Blobby' },
  359: { label: 'sidekick_chiliz', predicate: (a) => a['Sidekick'] === 'Chiliz' },
  360: { label: 'sidekick_copium_linctus_pro', predicate: (a) => a['Sidekick'] === 'Copium Linctus Pro' },
  361: { label: 'sidekick_cow', predicate: (a) => a['Sidekick'] === 'Cow' },
  362: { label: 'sidekick_d_balls', predicate: (a) => a['Sidekick'] === 'D Balls' },
  363: { label: 'sidekick_dancing_triangle', predicate: (a) => a['Sidekick'] === 'Dancing Triangle' },
  364: { label: 'sidekick_devil', predicate: (a) => a['Sidekick'] === 'Devil' },
  365: { label: 'sidekick_dexter', predicate: (a) => a['Sidekick'] === 'Dexter' },
  366: { label: 'sidekick_doll', predicate: (a) => a['Sidekick'] === 'Doll' },
  367: { label: 'sidekick_dragon', predicate: (a) => a['Sidekick'] === 'Dragon' },
  368: { label: 'sidekick_eddie', predicate: (a) => a['Sidekick'] === 'Eddie' },
  369: { label: 'sidekick_eli_owl', predicate: (a) => a['Sidekick'] === 'Eli Owl' },
  370: { label: 'sidekick_evil_alf', predicate: (a) => a['Sidekick'] === 'Evil Alf' },
  371: { label: 'sidekick_grim_reaper', predicate: (a) => a['Sidekick'] === 'Grim Reaper' },
  372: { label: 'sidekick_hey_mamma', predicate: (a) => a['Sidekick'] === 'Hey Mamma' },
  373: { label: 'sidekick_kazuya', predicate: (a) => a['Sidekick'] === 'Kazuya' },
  374: { label: 'sidekick_kekec', predicate: (a) => a['Sidekick'] === 'Kekec' },
  375: { label: 'sidekick_kevin_perry', predicate: (a) => a['Sidekick'] === 'Kevin Perry' },
  376: { label: 'sidekick_kevin_perry_2', predicate: (a) => a['Sidekick'] === 'Kevin Perry 2' },
  377: { label: 'sidekick_laughing', predicate: (a) => a['Sidekick'] === 'Laughing' },
  378: { label: 'sidekick_lean_harry', predicate: (a) => a['Sidekick'] === 'Lean Harry' },
  379: { label: 'sidekick_mojo', predicate: (a) => a['Sidekick'] === 'Mojo' },
  380: { label: 'sidekick_monkey_bomb', predicate: (a) => a['Sidekick'] === 'Monkey Bomb' },
  381: { label: 'sidekick_ogb', predicate: (a) => a['Sidekick'] === 'Ogb' },
  382: { label: 'sidekick_percy', predicate: (a) => a['Sidekick'] === 'PERCY' },
  383: { label: 'sidekick_pinky', predicate: (a) => a['Sidekick'] === 'Pinky' },
  384: { label: 'sidekick_ponziland', predicate: (a) => a['Sidekick'] === 'Ponziland' },
  385: { label: 'sidekick_purple_aki', predicate: (a) => a['Sidekick'] === 'Purple Aki' },
  386: { label: 'sidekick_randall', predicate: (a) => a['Sidekick'] === 'Randall' },
  387: { label: 'sidekick_schizo_barney', predicate: (a) => a['Sidekick'] === 'Schizo Barney' },
  388: { label: 'sidekick_schizo_barney_2', predicate: (a) => a['Sidekick'] === 'Schizo Barney 2' },
  389: { label: 'sidekick_sifu', predicate: (a) => a['Sidekick'] === 'Sifu' },
  390: { label: 'sidekick_slinky', predicate: (a) => a['Sidekick'] === 'Slinky' },
  391: { label: 'sidekick_sol_snatcher', predicate: (a) => a['Sidekick'] === 'Sol Snatcher' },
  392: { label: 'sidekick_toasty', predicate: (a) => a['Sidekick'] === 'Toasty' },
  393: { label: 'sidekick_tuff_times', predicate: (a) => a['Sidekick'] === 'Tuff Times' },
  394: { label: 'sidekick_weasel', predicate: (a) => a['Sidekick'] === 'Weasel' },
  395: { label: 'sidekick_yasin_sidekick', predicate: (a) => a['Sidekick'] === 'yasin sidekick ' },

  // === Weapons ===
  396: { label: 'weapons_ak47_pixel_green', predicate: (a) => a['Weapons'] === 'Ak47 Pixel Green' },
  397: { label: 'weapons_avnu_machete', predicate: (a) => a['Weapons'] === 'Avnu Machete' },
  398: { label: 'weapons_blades_sword', predicate: (a) => a['Weapons'] === 'Blades Sword' },
  399: { label: 'weapons_braavos_shield', predicate: (a) => a['Weapons'] === 'Braavos Shield' },
  400: { label: 'weapons_duck_hunt_gun', predicate: (a) => a['Weapons'] === 'Duck Hunt Gun' },
  401: { label: 'weapons_hyperlane_bazooka', predicate: (a) => a['Weapons'] === 'Hyperlane Bazooka' },
  402: { label: 'weapons_man_hunt_bat', predicate: (a) => a['Weapons'] === 'Man Hunt Bat' },
  403: { label: 'weapons_man_hunt_chainsaw', predicate: (a) => a['Weapons'] === 'Man Hunt Chainsaw' },
  404: { label: 'weapons_man_hunt_spade', predicate: (a) => a['Weapons'] === 'Man Hunt Spade' },
  405: { label: 'weapons_nigerian_gun', predicate: (a) => a['Weapons'] === 'Nigerian Gun' },
  406: { label: 'weapons_paradex_axe', predicate: (a) => a['Weapons'] === 'Paradex Axe' },
  407: { label: 'weapons_purps_hammer', predicate: (a) => a['Weapons'] === 'Purps Hammer' },
  408: { label: 'weapons_red_hammer', predicate: (a) => a['Weapons'] === 'Red Hammer' },
  409: { label: 'weapons_schizo_unicorn_blaster', predicate: (a) => a['Weapons'] === 'Schizo Unicorn Blaster' },
  410: { label: 'weapons_soul_sword', predicate: (a) => a['Weapons'] === 'Soul Sword' },
  411: { label: 'weapons_soul_sword_2', predicate: (a) => a['Weapons'] === 'Soul Sword 2' },
  412: { label: 'weapons_spamco_arcade_gun', predicate: (a) => a['Weapons'] === 'Spamco Arcade Gun' },
  413: { label: 'weapons_sushi_shooter', predicate: (a) => a['Weapons'] === 'Sushi Shooter' },
  414: { label: 'weapons_sword', predicate: (a) => a['Weapons'] === 'Sword' },
  415: { label: 'weapons_syrup_bat', predicate: (a) => a['Weapons'] === 'Syrup Bat' },
  416: { label: 'weapons_turkish_shooter', predicate: (a) => a['Weapons'] === 'Turkish Shooter' },
  417: { label: 'weapons_why_serious_shooter', predicate: (a) => a['Weapons'] === 'Why Serious Shooter' },
};

// Derive the 4-limb trait_bitmap for a given attributes record.
// Returns [limb0, limb1, limb2, limb3] where limb0 holds bits 0-127, etc.
export function computeBitmap(attrs: Record<string, string>): [bigint, bigint, bigint, bigint] {
  let bitmap = 0n;
  for (const [bitPos, { predicate }] of Object.entries(QUESTION_SCHEMA)) {
    if (predicate(attrs)) {
      bitmap |= (1n << BigInt(bitPos));
    }
  }
  const MASK = (1n << 128n) - 1n;
  return [
    (bitmap >>   0n) & MASK,
    (bitmap >> 128n) & MASK,
    (bitmap >> 256n) & MASK,
    (bitmap >> 384n) & MASK,
  ];
}
