// scripts/test-vectors.ts
// Generates fixture inputs for Noir circuit testing.
// Output: packages/circuits/Prover.toml
// Prerequisite: run prepare-collection.ts first.
// Run: npx tsx scripts/test-vectors.ts

import { readFileSync, mkdirSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';
import { computeLeaf, computeCommitment, verifyPath } from './merkle.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '..');

// Reproducible constants for test vectors
const TEST_SALT         = 0x1234567890abcdefn;
const TEST_GAME_ID      = 0x42n;
const TEST_TURN_ID      = 0x5n;
const TEST_PLAYER       = 0xdeadbeef1234n;
const TEST_CHARACTER_ID = 42;

function main() {
  // Read pre-generated collection data — no full tree rebuild needed.
  const mockPath = resolve(projectRoot, 'public/collections/schizodio.json');
  const mockData = JSON.parse(readFileSync(mockPath, 'utf8')) as {
    traits_root: string;
    characters: Array<{
      id: number;
      bitmap: string[];  // [limb0_hex, limb1_hex, limb2_hex, limb3_hex]
      merkle_path: string[];
      merkle_path_is_left: boolean[];
    }>;
  };

  const traitsRoot = BigInt(mockData.traits_root);
  const char = mockData.characters[TEST_CHARACTER_ID];
  if (char.id !== TEST_CHARACTER_ID) {
    throw new Error(`characters[${TEST_CHARACTER_ID}].id = ${char.id}, expected ${TEST_CHARACTER_ID}`);
  }

  const characterId = BigInt(TEST_CHARACTER_ID);
  // bitmap is now [limb0, limb1, limb2, limb3] (4-limb, one per 128 bits)
  const bitmapLimbs = (char.bitmap as string[]).map(s => BigInt(s)) as [bigint, bigint, bigint, bigint];
  const siblings = char.merkle_path.map(s => BigInt(s));
  const isLeft = char.merkle_path_is_left;

  // Verify the path against the root from mock.json (cross-checks prepare-collection output)
  const leaf = computeLeaf(characterId, bitmapLimbs);
  if (!verifyPath(leaf, TEST_CHARACTER_ID, siblings, isLeft, traitsRoot)) {
    throw new Error(`Merkle path for character ${TEST_CHARACTER_ID} does not verify — re-run prepare-collection.ts`);
  }

  // Commitment: Poseidon2([game_id, player, character_id, salt]) — BN254, matches Noir circuit.
  const commitment = computeCommitment(TEST_GAME_ID, TEST_PLAYER, characterId, TEST_SALT);

  // question_id=104 → body_snowflake (bit 104, Body bits 96-105 in new schema)
  const questionId = 104;
  // Extract the answer bit from the correct limb
  const limb = bitmapLimbs[Math.floor(questionId / 128)];
  const expectedAnswer = (limb >> BigInt(questionId % 128)) & 1n;

  console.log('Test vector:');
  console.log(`  character_id:    ${characterId} (Schizodio #${TEST_CHARACTER_ID})`);
  console.log(`  bitmap[0]:       0x${bitmapLimbs[0].toString(16)}`);
  console.log(`  question_id:     ${questionId} (body__snowflake, bit 104)`);
  console.log(`  expected_answer: ${expectedAnswer} (${expectedAnswer ? 'YES' : 'NO'})`);
  console.log(`  traits_root:     0x${traitsRoot.toString(16)}`);
  console.log(`  commitment:      0x${commitment.toString(16)}`);

  // Write Prover.toml — ALL values quoted as decimal strings for Noir Field/u128/u16 compatibility
  const proverToml = [
    '# Test witness for WhoisWho answer circuit',
    '# Generated by scripts/test-vectors.ts — DO NOT EDIT MANUALLY',
    '# Commitment = Poseidon2([game_id, player, character_id, salt]) — BN254.',
    '',
    '# === Public inputs ===',
    `game_id     = "${TEST_GAME_ID}"`,
    `turn_id     = "${TEST_TURN_ID}"`,
    `player      = "${TEST_PLAYER}"`,
    `commitment  = "${commitment}"`,
    `question_id = "${questionId}"`,
    `traits_root = "${traitsRoot}"`,
    '',
    '# === Private inputs ===',
    `character_id = "${characterId}"`,
    `salt         = "${TEST_SALT}"`,
    `trait_bitmap = [${bitmapLimbs.map(l => '"' + l + '"').join(', ')}]`,
    `merkle_path  = [${siblings.map(s => '"' + s + '"').join(', ')}]`,
  ].join('\n');

  const outDir = resolve(projectRoot, 'packages/circuits');
  mkdirSync(outDir, { recursive: true });
  const outFile = resolve(outDir, 'Prover.toml');
  writeFileSync(outFile, proverToml);
  console.log(`✓ Written: ${outFile}`);
}

main();
